import numpy as np
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Union, Dict, Any, Optional


class DataType(Enum):
    """Data types for standardized processing"""
    SCALAR = "scalar"  # Simple float values (e.g., temperature, speed)
    WAVEFORM = "waveform"  # Time-series arrays (e.g., vibration raw data)
    SPECTRUM = "spectrum"  # Frequency domain arrays
    HEALTH_SCORE = "health"  # Calculated health indices
    FAULT = "fault"  # Diagnosis results


class SignalSource(Enum):
    """Origin of the data"""
    MODBUS = "modbus"
    MQTT = "mqtt"
    FILE = "file"
    SIMULATION = "simulation"
    INTERNAL = "internal"  # Generated by the system itself (e.g., health scores)


@dataclass
class DataPoint:
    """
    The atomic unit of data in the system.

    All collectors must convert their raw inputs into this format before
    sending to the Global Queue.
    """
    # Essential metadata
    timestamp: datetime
    source: SignalSource
    type: DataType

    # Identification
    device_name: str
    point_name: str

    # The actual payload
    # Scalar values are floats; Waveforms are numpy arrays
    value: Union[float, np.ndarray, Dict[str, Any], str]

    # Additional context (units, sampling rate, etc.)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validation to ensure data integrity"""
        if self.type == DataType.WAVEFORM and not isinstance(self.value, (np.ndarray, list)):
            raise ValueError(f"Waveform data must be array-like, got {type(self.value)}")

        if self.type == DataType.SCALAR:
            try:
                self.value = float(self.value)
            except (ValueError, TypeError):
                # Allow non-numeric scalars (e.g., status strings) if necessary,
                # but log warning in a real system. For now, keep strict.
                pass


@dataclass
class DiagnosisResult:
    """Standardized output from the Diagnosis Engine"""
    timestamp: datetime
    device_name: str
    health_score: float
    faults: list[Dict[str, Any]] = field(default_factory=list)
    features: Dict[str, float] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)